import os
import django

# Replace myproject with your project folder name
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "backend.settings")  
django.setup()



words=[
  {"text":"Appreciate","meaning":"To recognize the value of something","example":"I really appreciate your help."},
  {"text":"Consider","meaning":"To think carefully about something","example":"I will consider your suggestion."},
  {"text":"Convenient","meaning":"Easy and suitable for someone","example":"Online shopping is very convenient."},
  {"text":"Confident","meaning":"Sure of yourself","example":"She feels confident about the exam."},
  {"text":"Curious","meaning":"Wanting to know more","example":"The child is curious about animals."},
  {"text":"Encourage","meaning":"To give support or confidence","example":"Teachers encourage students to ask questions."},
  {"text":"Experience","meaning":"Knowledge gained by doing","example":"I have work experience in marketing."},
  {"text":"Flexible","meaning":"Able to change easily","example":"My schedule is flexible this week."},
  {"text":"Frustrated","meaning":"Feeling annoyed or upset","example":"He was frustrated with the slow internet."},
  {"text":"Grateful","meaning":"Feeling thankful","example":"I am grateful for your kindness."},
  {"text":"Important","meaning":"Of great value","example":"It’s important to drink enough water."},
  {"text":"Impress","meaning":"To make someone admire you","example":"Her speech impressed the audience."},
  {"text":"Independent","meaning":"Not depending on others","example":"She is an independent thinker."},
  {"text":"Interesting","meaning":"Holding attention","example":"This documentary is very interesting."},
  {"text":"Interrupt","meaning":"To stop someone speaking","example":"Please don’t interrupt me while I talk."},
  {"text":"Introduce","meaning":"To make someone known","example":"Let me introduce you to my friend."},
  {"text":"Manage","meaning":"To handle or control","example":"She can manage both work and study."},
  {"text":"Mention","meaning":"To talk about briefly","example":"He didn’t mention the problem yesterday."},
  {"text":"Motivate","meaning":"To inspire someone to act","example":"Good leaders motivate their teams."},
  {"text":"Necessary","meaning":"Needed or essential","example":"It’s necessary to wear a helmet."},
  {"text":"Opportunity","meaning":"A chance to do something","example":"This job is a great opportunity."},
  {"text":"Organize","meaning":"Arrange in order","example":"We need to organize the files."},
  {"text":"Patient","meaning":"Able to wait calmly","example":"Be patient while I finish this work."},
  {"text":"Polite","meaning":"Having good manners","example":"It’s polite to say thank you."},
  {"text":"Positive","meaning":"Hopeful and confident","example":"Stay positive even in hard times."},
  {"text":"Possibility","meaning":"Something that may happen","example":"There’s a possibility of rain tomorrow."},
  {"text":"Prefer","meaning":"To like something more","example":"I prefer tea over coffee."},
  {"text":"Prepare","meaning":"To get ready","example":"I need to prepare for my test."},
  {"text":"Problem","meaning":"A difficult situation","example":"We must solve this problem quickly."},
  {"text":"Promise","meaning":"A commitment to do something","example":"I promise to help you tomorrow."},
  {"text":"Provide","meaning":"To give or supply","example":"The hotel will provide free breakfast."},
  {"text":"Receive","meaning":"To get something","example":"I received a gift from my friend."},
  {"text":"Recommend","meaning":"To suggest something","example":"Can you recommend a good restaurant?"},
  {"text":"Reduce","meaning":"To make smaller","example":"We must reduce plastic use."},
  {"text":"Refuse","meaning":"To say no","example":"He refused to answer the question."},
  {"text":"Relax","meaning":"To rest and feel calm","example":"I like to relax on weekends."},
  {"text":"Remember","meaning":"To keep in mind","example":"I remember meeting her last year."},
  {"text":"Replace","meaning":"To put something new in place of old","example":"I need to replace my old shoes."},
  {"text":"Require","meaning":"To need something","example":"This job requires strong English skills."},
  {"text":"Respect","meaning":"To show regard or honor","example":"We must respect our parents."},
  {"text":"Respond","meaning":"To reply","example":"He didn’t respond to my message."},
  {"text":"Suggest","meaning":"To give an idea","example":"Can you suggest a good movie?"},
  {"text":"Support","meaning":"To help or encourage","example":"Family support is very important."},
  {"text":"Surprised","meaning":"Feeling shocked or amazed","example":"I was surprised by the news."},
  {"text":"Understand","meaning":"To know the meaning","example":"Do you understand this lesson?"},
  {"text":"Useful","meaning":"Helpful or practical","example":"This dictionary is very useful."},
  {"text":"Usually","meaning":"Most of the time","example":"I usually go jogging in the morning."},
  {"text":"Welcome","meaning":"To greet kindly","example":"You are always welcome here."},
  {"text":"Wonderful","meaning":"Extremely good","example":"We had a wonderful holiday."},
  {"text":"Worried","meaning":"Anxious about something","example":"I am worried about my exam results."},
  {"text": "Nimble", "meaning": "Quick and light in movement or action", "example": "The cat was nimble as it jumped across the fence."},
  {"text": "Obedient", "meaning": "Complying or willing to comply with orders or requests", "example": "The dog was obedient to its trainer."},
  {"text": "Patient", "meaning": "Able to accept or tolerate delays or problems without getting angry", "example": "You need to be patient when learning a new skill."},
  {"text": "Quiet", "meaning": "Making little or no noise", "example": "The library was quiet during study hours."},
  {"text": "Reliable", "meaning": "Consistently good in quality or performance; able to be trusted", "example": "He is a reliable friend."},
  {"text": "Sincere", "meaning": "Free from pretense or deceit; genuine", "example": "Her apology was sincere."},
  {"text": "Trustworthy", "meaning": "Able to be relied on as honest or truthful", "example": "A trustworthy person keeps their promises."},
  {"text": "Understanding", "meaning": "Sympathetically aware of other people's feelings", "example": "She was understanding when I explained my situation."},
  {"text": "Valiant", "meaning": "Possessing or showing courage or determination", "example": "The valiant firefighter rescued the child."},
  {"text": "Wise", "meaning": "Having experience, knowledge, and good judgment", "example": "It was wise of him to save money for emergencies."},
  {"text": "Xenial", "meaning": "Friendly relations between host and guest", "example": "The innkeeper was xenial and welcoming to all travelers."},
  {"text": "Youthful", "meaning": "Having the qualities of youth; lively and energetic", "example": "She had a youthful enthusiasm for learning."},
  {"text": "Zealous", "meaning": "Having or showing great energy or enthusiasm in pursuit of a cause", "example": "He was zealous in volunteering for the community service."},
  {"text": "Adorable", "meaning": "Inspiring great affection; delightful", "example": "The puppy was absolutely adorable."},
  {"text": "Brave", "meaning": "Ready to face and endure danger or pain; showing courage", "example": "The soldier was brave during the battle."},
  {"text": "Creative", "meaning": "Relating to or involving the use of imagination to produce original ideas", "example": "She is very creative in painting."},
  {"text": "Decent", "meaning": "Conforming with generally accepted standards of respectable behavior", "example": "He is a decent person who helps others."},
  {"text": "Energetic", "meaning": "Showing or involving great activity or vitality", "example": "The kids were energetic all morning."},
  {"text": "Friendly", "meaning": "Kind and pleasant", "example": "The receptionist was very friendly."},
  {"text": "Generous", "meaning": "Willing to give more than necessary or expected", "example": "She was generous with her time."},
  {"text": "Helpful", "meaning": "Providing assistance or serving a useful function", "example": "The guide was very helpful."},
  {"text": "Imaginative", "meaning": "Having a creative mind or a good imagination", "example": "The child wrote an imaginative story."},
  {"text": "Joyful", "meaning": "Feeling, expressing, or causing great pleasure and happiness", "example": "The children were joyful on the playground."},
  {"text": "Kindhearted", "meaning": "Having a kind and sympathetic nature", "example": "She is kindhearted and always helps the needy."},
  {"text": "Lively", "meaning": "Full of life and energy; active and outgoing", "example": "The party was lively and fun."},
  {"text": "Modest", "meaning": "Unassuming in the estimation of one's abilities or achievements", "example": "He is modest despite his success."},
  {"text": "Neat", "meaning": "Arranged in an orderly, tidy way", "example": "Her handwriting is very neat."},
  {"text": "Optimistic", "meaning": "Hopeful and confident about the future", "example": "She remained optimistic about the results."},
  {"text": "Polished", "meaning": "Refined, elegant, or sophisticated", "example": "He gave a polished presentation."},
  {"text": "Quick-witted", "meaning": "Showing or characterized by an ability to think or respond quickly and effectively", "example": "She is quick-witted in debates."},
  {"text": "Respectful", "meaning": "Feeling or showing deference and respect", "example": "The student was respectful to the teacher."},
  {"text": "Skillful", "meaning": "Having or showing skill", "example": "The surgeon is very skillful."},
  {"text": "Thoughtful", "meaning": "Showing consideration for the needs of others", "example": "It was thoughtful of her to send a gift."},
  {"text": "Upbeat", "meaning": "Cheerful and optimistic", "example": "He remained upbeat despite the setback."},
  {"text": "Versatile", "meaning": "Able to adapt or be adapted to many different functions or activities", "example": "She is a versatile athlete."},
  {"text": "Warmhearted", "meaning": "Kind, sympathetic, and friendly", "example": "He is warmhearted and generous."},
  {"text": "Xenodochial", "meaning": "Friendly to strangers or foreigners", "example": "The community is xenodochial and welcoming."},
  {"text": "Youthful", "meaning": "Having the qualities of youth; lively and energetic", "example": "He maintained a youthful spirit."},
  {"text": "Zany", "meaning": "Amusingly unconventional and idiosyncratic", "example": "He has a zany sense of humor."},
    {"text": "Abandon", "meaning": "To leave behind or give up on something or someone", "example": "The ship was abandoned after the storm."},
  {"text": "Benevolent", "meaning": "Well-meaning and kindly", "example": "She was a benevolent leader who cared for her people."},
  {"text": "Cautious", "meaning": "Careful to avoid potential problems or dangers", "example": "Be cautious when crossing the street."},
  {"text": "Diligent", "meaning": "Having or showing care and conscientiousness in one's work or duties", "example": "He was diligent in his studies."},
  {"text": "Eloquent", "meaning": "Fluent or persuasive in speaking or writing", "example": "The speaker gave an eloquent speech on human rights."},
  {"text": "Frivolous", "meaning": "Not having any serious purpose or value", "example": "She made a frivolous purchase."},
  {"text": "Grim", "meaning": "Forbidding or uninviting", "example": "The news was grim."},
  {"text": "Harmonious", "meaning": "Forming a pleasing or consistent whole", "example": "They lived in harmonious coexistence."},
  {"text": "Innocuous", "meaning": "Not harmful or offensive", "example": "The comment was innocuous."},
  {"text": "Jubilant", "meaning": "Feeling or expressing great happiness and joy", "example": "The crowd was jubilant after the victory."},
  {"text": "Keen", "meaning": "Having or showing eagerness or enthusiasm", "example": "She was keen to start her new job."},
  {"text": "Luminous", "meaning": "Full of or shedding light; bright or shining", "example": "The luminous moon lit up the night sky."},
  {"text": "Meticulous", "meaning": "Showing great attention to detail; very careful and precise", "example": "He was meticulous in his work."},
  {"text": "Noble", "meaning": "Having or showing fine personal qualities or high moral principles", "example": "He was a noble man."},
  {"text": "Oblivious", "meaning": "Not aware of or concerned about what is happening around one", "example": "She was oblivious to the danger."},
  {"text": "Plausible", "meaning": "Seeming reasonable or probable", "example": "His explanation was plausible."},
  {"text": "Quaint", "meaning": "Attractively unusual or old-fashioned", "example": "They stayed in a quaint cottage."},
  {"text": "Resilient", "meaning": "Able to withstand or recover quickly from difficult conditions", "example": "The community was resilient after the disaster."},
  {"text": "Serene", "meaning": "Calm, peaceful, and untroubled", "example": "The lake was serene in the morning."},
  {"text": "Tangible", "meaning": "Perceptible by touch", "example": "The tension in the room was tangible."},
  {"text": "Ubiquitous", "meaning": "Present, appearing, or found everywhere", "example": "Smartphones are ubiquitous in today's society."},
  {"text": "Vivid", "meaning": "Producing powerful feelings or strong, clear images in the mind", "example": "She gave a vivid description of the event."},
  {"text": "Witty", "meaning": "Showing or characterized by quick and inventive verbal humor", "example": "He made a witty remark."},
  {"text": "Xenial", "meaning": "Relating to hospitality or relations between host and guest", "example": "The hotel staff was xenial."},
  {"text": "Yearn", "meaning": "To have an intense feeling of longing for something", "example": "She yearned for a peaceful life."},
  {"text": "Zealous", "meaning": "Having or showing zeal; passionate", "example": "He was zealous in his support for the cause."},
  {"text": "Altruistic", "meaning": "Showing a selfless concern for the well-being of others", "example": "Her altruistic nature made her popular."},
  {"text": "Brevity", "meaning": "Concise and exact use of words in writing or speech", "example": "The brevity of his speech was appreciated."},
  {"text": "Camaraderie", "meaning": "Mutual trust and friendship among people who spend a lot of time together", "example": "There was a sense of camaraderie among the team."},
  {"text": "Decisive", "meaning": "Settling an issue; producing a definite result", "example": "Her decisive actions saved the company."},
  {"text": "Empathy", "meaning": "The ability to understand and share the feelings of another", "example": "She showed great empathy towards the victims."},
  {"text": "Fortitude", "meaning": "Courage in pain or adversity", "example": "He showed fortitude during the crisis."},
  {"text": "Gratitude", "meaning": "The quality of being thankful; readiness to show appreciation", "example": "She expressed her gratitude for the help."},
  {"text": "Humility", "meaning": "A modest or low view of one's importance", "example": "His humility was admired by all."},
  {"text": "Integrity", "meaning": "The quality of being honest and having strong moral principles", "example": "He is a man of integrity."},
  {"text": "Jovial", "meaning": "Cheerful and friendly", "example": "She had a jovial personality."},
  {"text": "Keen", "meaning": "Having or showing eagerness or enthusiasm", "example": "He was keen to learn new skills."},
  {"text": "Loyal", "meaning": "Giving or showing firm and constant support or allegiance", "example": "She remained loyal to her friends."},
  {"text": "Mature", "meaning": "Fully developed physically; full-grown", "example": "He is a mature individual."},
  {"text": "Nurture", "meaning": "Care for and encourage the growth or development of", "example": "Parents should nurture their children's talents."},
  {"text": "Optimistic", "meaning": "Hopeful and confident about the future", "example": "She remained optimistic despite the challenges."},
  {"text": "Pragmatic", "meaning": "Dealing with things sensibly and realistically", "example": "He took a pragmatic approach to the problem."},
  {"text": "Quaint", "meaning": "Attractively unusual or old-fashioned", "example": "They visited a quaint village."},
  {"text": "Resilient", "meaning": "Able to withstand or recover quickly from difficult conditions", "example": "The community was resilient after the disaster."},
  {"text": "Sympathetic", "meaning": "Feeling, showing, or expressing sympathy", "example": "She was sympathetic towards the victims."},
  {"text": "Tolerant", "meaning": "Showing willingness to allow the existence of opinions or behavior that one does not necessarily agree with", "example": "He was tolerant of different viewpoints."},
  {"text": "Unique", "meaning": "Being the only one of its kind; unlike anything else", "example": "Each person's fingerprint is unique."},
  {"text": "Vibrant", "meaning": "Full of energy and enthusiasm", "example": "The city has a vibrant nightlife."},
  {"text": "Wise", "meaning": "Having or showing experience, knowledge, and good judgment", "example": "He is a wise old man."},
  {"text": "Xenophobic", "meaning": "Having or showing a dislike of or prejudice against people from other countries", "example": "His xenophobic remarks were condemned."},
  {"text": "Youthful", "meaning": "Having the appearance, freshness, or energy of youth", "example": "She had a youthful appearance."},
  {"text": "Zealous", "meaning": "Having or showing zeal; passionate", "example": "He was zealous in his support for the cause."},
  {"text": "Adventurous", "meaning": "Willing to take risks or try out new methods, ideas, or experiences", "example": "She had an adventurous spirit."},
  {"text": "Brilliant", "meaning": "Exceptionally clever or talented", "example": "He gave a brilliant performance."},
  {"text": "Courageous", "meaning": "Not deterred by danger or pain; brave", "example": "The courageous soldier saved his comrades."},
  {"text": "Determined", "meaning": "Having made a firm decision and being resolved not to change it", "example": "She was determined to succeed."},
  {"text": "Empathetic", "meaning": "Showing an ability to understand and share the feelings of another", "example": "He was empathetic towards the refugees."},
  {"text": "Faithful", "meaning": "Remaining loyal and steadfast", "example": "She remained faithful to her beliefs."},
  {"text": "Generous", "meaning": "Showing kindness towards others", "example": "He made a generous donation."},
  {"text": "Honest", "meaning": "Free of deceit; truthful and sincere", "example": "She gave an honest answer."},
  {"text": "Innovative", "meaning": "Featuring new methods; advanced and original", "example": "The company is known for its innovative products."},
  {"text": "Judicious", "meaning": "Having, showing, or done with good judgment or sense", "example": "He made a judicious decision."},
  {"text": "Abandon", "meaning": "To leave behind or give up completely", "example": "She decided to abandon the project due to lack of resources."},
  {"text": "Benevolent", "meaning": "Well meaning and kindly", "example": "The benevolent leader donated a large sum to charity."},
  {"text": "Cacophony", "meaning": "A harsh, discordant mixture of sounds", "example": "The city street was filled with the cacophony of honking horns."},
  {"text": "Diligent", "meaning": "Having or showing care and conscientiousness in one's work or duties", "example": "She was diligent in her studies, always completing assignments on time."},
  {"text": "Eloquent", "meaning": "Fluent or persuasive in speaking or writing", "example": "The speaker gave an eloquent speech that moved the audience."},
  {"text": "Futile", "meaning": "Incapable of producing any useful result; pointless", "example": "Their efforts to fix the old car were futile."},
  {"text": "Garrulous", "meaning": "Excessively talkative, especially on trivial matters", "example": "The garrulous neighbor kept us up all night with his stories."},
  {"text": "Hapless", "meaning": "Unfortunate or unlucky", "example": "The hapless traveler lost his passport on the first day of his trip."},
  {"text": "Incessant", "meaning": "Continuing without pause or interruption", "example": "The incessant noise from the construction site was unbearable."},
  {"text": "Juxtapose", "meaning": "To place or deal with close together for contrasting effect", "example": "The artist juxtaposed light and dark colors in the painting."},
  {"text": "Keen", "meaning": "Having a sharp edge or point; highly developed", "example": "She has a keen sense of smell."},
  {"text": "Lament", "meaning": "To mourn or express sorrow", "example": "He lamented the loss of his childhood home."},
  {"text": "Mellifluous", "meaning": "Sweet or musical; pleasant to hear", "example": "The singer's mellifluous voice captivated the audience."},
  {"text": "Nefarious", "meaning": "Wicked or criminal", "example": "The nefarious activities of the gang were exposed by the police."},
  {"text": "Obfuscate", "meaning": "To deliberately make something unclear or difficult to understand", "example": "The politician tried to obfuscate the issue with vague statements."},
  {"text": "Pernicious", "meaning": "Having a harmful effect, especially in a gradual or subtle way", "example": "The pernicious effects of smoking are well-documented."},
  {"text": "Quixotic", "meaning": "Extremely idealistic; unrealistic and impractical", "example": "His quixotic quest for perfection led to constant disappointment."},
  {"text": "Recalcitrant", "meaning": "Having an obstinately uncooperative attitude", "example": "The recalcitrant student refused to follow the school's rules."},
  {"text": "Sycophant", "meaning": "A person who acts obsequiously towards someone important in order to gain advantage", "example": "The sycophant flattered the boss to get a promotion."},
  {"text": "Tantamount", "meaning": "Equivalent in seriousness to; virtually the same as", "example": "His actions were tantamount to betrayal."},
  {"text": "Ubiquitous", "meaning": "Present, appearing, or found everywhere", "example": "Smartphones are ubiquitous in modern society."},
  {"text": "Voracious", "meaning": "Wanting or devouring great quantities of food; having a very eager approach to a particular activity", "example": "She has a voracious appetite for reading."},
  {"text": "Wistful", "meaning": "Longing or yearning for something that may never be attained", "example": "He gave a wistful look at the old photographs."},
  {"text": "Xenophobic", "meaning": "Having or showing a dislike of or prejudice against people from other countries", "example": "The xenophobic remarks were condemned by the community."},
  {"text": "Yen", "meaning": "A strong desire or craving", "example": "He had a yen for adventure."},
  {"text": "Zephyr", "meaning": "A gentle, mild breeze", "example": "The zephyr brought a cool relief on the hot day."},
  {"text": "Apathy", "meaning": "Lack of interest, enthusiasm, or concern", "example": "The student's apathy towards the subject was evident."},
  {"text": "Brevity", "meaning": "Concise and exact use of words in writing or speech", "example": "The brevity of his speech impressed the audience."},
  {"text": "Camaraderie", "meaning": "Mutual trust and friendship among people who spend a lot of time together", "example": "The camaraderie among teammates was evident."},
  {"text": "Debilitate", "meaning": "To make someone weak and infirm", "example": "The illness debilitated him for weeks."},
  {"text": "Ebullient", "meaning": "Cheerful and full of energy", "example": "Her ebullient personality brightened up the room."},
  {"text": "Facilitate", "meaning": "To make an action or process easy or easier", "example": "The new software will facilitate the workflow."},
  {"text": "Gregarious", "meaning": "Fond of company; sociable", "example": "He was a gregarious man who loved parties."},
  {"text": "Haploid", "meaning": "Having a single set of unpaired chromosomes", "example": "Gametes are haploid cells."},
  {"text": "Infallible", "meaning": "Incapable of making mistakes or being wrong", "example": "The scientist believed in the infallible nature of his theory."},
  {"text": "Juxtaposition", "meaning": "The fact of two things being seen or placed close together with contrasting effect", "example": "The juxtaposition of the old and new buildings was striking."},
  {"text": "Kaleidoscope", "meaning": "A constantly changing pattern or sequence of elements", "example": "The city lights at night created a kaleidoscope of colors."},
  {"text": "Lethargic", "meaning": "Affected by lethargy; sluggish and apathetic", "example": "The hot weather made everyone feel lethargic."},
  {"text": "Munificent", "meaning": "More generous than is usual or necessary", "example": "The munificent donation helped build the new library."},
  {"text": "Noxious", "meaning": "Harmful, poisonous, or very unpleasant", "example": "The noxious fumes from the factory caused health issues."},
  {"text": "Ostentatious", "meaning": "Characterized by vulgar or pretentious display; designed to impress or attract notice", "example": "His ostentatious display of wealth was off-putting."},
  {"text": "Pusillanimous", "meaning": "Showing a lack of courage or determination; timid", "example": "The pusillanimous response to the challenge was disappointing."},
  {"text": "Quintessential", "meaning": "Representing the most perfect or typical example of a quality or class", "example": "She is the quintessential romantic heroine."},
  {"text": "Recalcitrant", "meaning": "Having an obstinately uncooperative attitude", "example": "The recalcitrant student refused to follow the school's rules."},
  {"text": "Sycophant", "meaning": "A person who acts obsequiously towards someone important in order to gain advantage", "example": "The sycophant flattered the boss to get a promotion."},
  {"text": "Tantamount", "meaning": "Equivalent in seriousness to; virtually the same as", "example": "His actions were tantamount to betrayal."},
  {"text": "Ubiquitous", "meaning": "Present, appearing, or found everywhere", "example": "Smartphones are ubiquitous in modern society."},
  {"text": "Voracious", "meaning": "Wanting or devouring great quantities of food; having a very eager approach to a particular activity", "example": "She has a voracious appetite for reading."},
  {"text": "Wistful", "meaning": "Longing or yearning for something that may never be attained", "example": "He gave a wistful look at the old photographs."},
  {"text": "Xenophobic", "meaning": "Having or showing a dislike of or prejudice against people from other countries", "example": "The xenophobic remarks were condemned by the community."},
  {"text": "Yen", "meaning": "A strong desire or craving", "example": "He had a yen for adventure."},
  {"text": "Zephyr", "meaning": "A gentle, mild breeze", "example": "The zephyr brought a cool relief on the hot day."},
  {"text": "Apathy", "meaning": "Lack of interest, enthusiasm, or concern", "example": "The student's apathy towards the subject was evident."},
  {"text": "Brevity", "meaning": "Concise and exact use of words in writing or speech", "example": "The brevity of his speech impressed the audience."},
  {"text": "Camaraderie", "meaning": "Mutual trust and friendship among people who spend a lot of time together", "example": "The camaraderie among teammates was evident."},
  {"text": "Debilitate", "meaning": "To make someone weak and infirm", "example": "The illness debilitated him for weeks."},
  {"text": "Ebullient", "meaning": "Cheerful and full of energy", "example": "Her ebullient personality brightened up the room."},
  {"text": "Facilitate", "meaning": "To make an action or process easy or easier", "example": "The new software will facilitate the workflow."},


  
]
from words.models import Word

for w in words:
    Word.objects.update_or_create(
        text=w['text'].strip().lower(),  # normalize text to avoid duplicates
        defaults={
            'meaning': w['meaning'],
            'example': w['example']
        }
    )
    
print("✅ 50 words inserted/updated successfully!")