# Generated by Django 5.2.6 on 2025-09-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
