# Generated by Django 5.2.6 on 2025-09-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_quizquestionattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestionattempt',
            name='selected_answer',
        ),
    ]
